version: '3.8'

services:
  mibarber:
    image: mibarber:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mibarber.rule=Host(`mibarber.codexa.uy`)"
        - "traefik.http.routers.mibarber.entrypoints=websecure"
        - "traefik.http.routers.mibarber.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.mibarber.loadbalancer.server.port=3000"
        - "traefik.docker.network=oraclelabsnet"
        # Redirect HTTP to HTTPS
        - "traefik.http.routers.mibarber-http.rule=Host(`mibarber.codexa.uy`)"
        - "traefik.http.routers.mibarber-http.entrypoints=web"
        - "traefik.http.routers.mibarber-http.middlewares=redirect-to-https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
    networks:
      - oraclelabsnet
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_SUPABASE_URL=https://supapers.itmconsulting.es
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.ewogICJyb2xlIjogImFub24iLAogICJpc3MiOiAic3VwYWJhc2UiLAogICJpYXQiOiAxNzE1MDUwODAwLAogICJleHAiOiAxODcyODE3MjAwCn0.qPYvk4GYIxKU-fVHDbTD3TYHo5eTsGp17EszifM2n2Q

networks:
  oraclelabsnet:
    external: true